-- AlterTable
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PathologyPartner" ADD COLUMN IF NOT EXISTS "serviceRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 3;
